In [1]:
import pandas as pd
import os
from utils.change_column_names import changeToName
from utils.feature_engineering import *
from utils.data_loader import *

os.listdir()
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [2]:
data = pd.read_csv('sample_tickdata.csv')
data.head()

,COLUMN01,COLUMN02,COLUMN03,COLUMN04,COLUMN05,COLUMN06,COLUMN07,COLUMN08,COLUMN09,COLUMN10,COLUMN11,COLUMN12,COLUMN13,COLUMN14,COLUMN15,COLUMN16,COLUMN17,COLUMN18,COLUMN19,COLUMN20,COLUMN21,COLUMN22,COLUMN23,COLUMN24,COLUMN25,COLUMN26,COLUMN27,COLUMN28,COLUMN29,COLUMN30,COLUMN31,COLUMN32,COLUMN33,COLUMN34,COLUMN35,COLUMN36,COLUMN37,COLUMN38,COLUMN39,COLUMN40,COLUMN41,COLUMN42,COLUMN43,COLUMN44,COLUMN45,COLUMN46,COLUMN47,COLUMN48,COLUMN49,COLUMN50,COLUMN51,COLUMN52,COLUMN53,COLUMN54,COLUMN55
0,20,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,189900,190000,190200,190300,190400,190500,190600,1000,13400,4100,10900,6500,800,11500,100,1000,300,189100,189000,188900,188800,188600,188500,188400,188300,188200,188100,600,200,4100,900,600,3100,700,38700,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
1,28,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,189900,190000,190200,190300,190400,190500,190600,1000,13400,4100,10900,6500,800,11500,100,1000,300,189100,189000,188900,188800,188600,188500,188400,188300,188200,188100,600,200,4100,900,600,3100,700,38700,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
2,39,002156.SZ,93000000,170900,171000,170500,170900,171000,171200,171600,171800,171900,172000,172200,172300,172400,172500,2700,600,200,1500,1200,12000,400,100,400,700,170900,170700,170600,170500,170400,170300,170200,170100,170000,169900,3000,21600,500,13400,9900,40600,5600,23900,39200,800,517700,8846992,920700,1106300,190400,155800,163100,182900
3,40,002156.SZ,93000000,170900,171000,170500,170900,171000,171200,171600,171800,171900,172000,172200,172300,172400,172500,2700,600,200,1500,1200,12000,400,100,400,700,170900,170700,170600,170500,170400,170300,170200,170100,170000,169900,3000,21600,500,13400,9900,40600,5600,23900,39200,800,517700,8846992,920700,1106300,190400,155800,163100,182900
4,63,002153.SZ,93000000,148000,148800,147900,147900,148600,148700,148800,149500,149600,149800,149900,150000,150300,150400,3500,1000,1100,4000,200,1800,12800,10000,1000,8900,147900,147800,147600,147000,146500,146400,146100,146000,145800,145700,500,500,2400,2600,5900,3100,1000,300,2000,10900,47700,706052,325100,239420,163700,133900,141800,153500

In [3]:
data = changeToName(data)
data.head()

,Index,StockCode,TickTime,OpeningPrice,HighestPriceToTick,LowestPriceToTick,LatestTransactionPriceToTick,SellingPrice1,SellingPrice2,SellingPrice3,SellingPrice4,SellingPrice5,SellingPrice6,SellingPrice7,SellingPrice8,SellingPrice9,SellingPrice10,SellingVolume1,SellingVolume2,SellingVolume3,SellingVolume4,SellingVolume5,SellingVolume6,SellingVolume7,SellingVolume8,SellingVolume9,SellingVolume10,BuyingPrice1,BuyingPrice2,BuyingPrice3,BuyingPrice4,BuyingPrice5,BuyingPrice6,BuyingPrice7,BuyingPrice8,BuyingPrice9,BuyingPrice10,BuyingVolume1,BuyingVolume2,BuyingVolume3,BuyingVolume4,BuyingVolume5,BuyingVolume6,BuyingVolume7,BuyingVolume8,BuyingVolume9,BuyingVolume10,CumulativeTransactionVolumeToTick,CumulativeTransactionAmountToTick,TotalCommissionedBuyingVolumeToTick,TotalCommissionedSellingVolumeToTick,LimitUpPrice,LimitDownPrice,WeightedAverageCommissionedBuyingPriceToTick,WeightedAverageCommissionedSellingPriceToTick
0,20,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,189900,190000,190200,190300,190400,190500,190600,1000,13400,4100,10900,6500,800,11500,100,1000,300,189100,189000,188900,188800,188600,188500,188400,188300,188200,188100,600,200,4100,900,600,3100,700,38700,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
1,28,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,189900,190000,190200,190300,190400,190500,190600,1000,13400,4100,10900,6500,800,11500,100,1000,300,189100,189000,188900,188800,188600,188500,188400,188300,188200,188100,600,200,4100,900,600,3100,700,38700,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
2,39,002156.SZ,93000000,170900,171000,170500,170900,171000,171200,171600,171800,171900,172000,172200,172300,172400,172500,2700,600,200,1500,1200,12000,400,100,400,700,170900,170700,170600,170500,170400,170300,170200,170100,170000,169900,3000,21600,500,13400,9900,40600,5600,23900,39200,800,517700,8846992,920700,1106300,190400,155800,163100,182900
3,40,002156.SZ,93000000,170900,171000,170500,170900,171000,171200,171600,171800,171900,172000,172200,172300,172400,172500,2700,600,200,1500,1200,12000,400,100,400,700,170900,170700,170600,170500,170400,170300,170200,170100,170000,169900,3000,21600,500,13400,9900,40600,5600,23900,39200,800,517700,8846992,920700,1106300,190400,155800,163100,182900
4,63,002153.SZ,93000000,148000,148800,147900,147900,148600,148700,148800,149500,149600,149800,149900,150000,150300,150400,3500,1000,1100,4000,200,1800,12800,10000,1000,8900,147900,147800,147600,147000,146500,146400,146100,146000,145800,145700,500,500,2400,2600,5900,3100,1000,300,2000,10900,47700,706052,325100,239420,163700,133900,141800,153500

In [4]:
wa = NDayRegression()
datax = wa.transform(data)

In [5]:
datax.sort_values(['StockCode', 'TickTime']).head(20)[["LatestTransactionPriceToTick", '5_reg']]

     LatestTransactionPriceToTick  5_reg
60                          38600    NaN
61                          38600    NaN
114                         38400    NaN
148                         38400    NaN
214                         38500    NaN
264                         38500  -10.0
309                         38500   30.0
364                         38500   20.0
382                         38500    0.0
433                         38400  -20.0
518                         38400  -30.0
548                         38500  -10.0
615                         38500   10.0
648                         38500   30.0
716                         38500   20.0
761                         38400  -20.0
814                         38400  -30.0
862                         38400  -30.0
911                         38300  -40.0
961                         38300  -30.0

In [6]:
data[data['StockCode'] == '000031.SZ']

,Index,StockCode,TickTime,OpeningPrice,HighestPriceToTick,LowestPriceToTick,LatestTransactionPriceToTick,SellingPrice1,SellingPrice2,SellingPrice3,SellingPrice4,SellingPrice5,SellingPrice6,SellingPrice7,SellingPrice8,SellingPrice9,SellingPrice10,SellingVolume1,SellingVolume2,SellingVolume3,SellingVolume4,SellingVolume5,SellingVolume6,SellingVolume7,SellingVolume8,SellingVolume9,SellingVolume10,BuyingPrice1,BuyingPrice2,BuyingPrice3,BuyingPrice4,BuyingPrice5,BuyingPrice6,BuyingPrice7,BuyingPrice8,BuyingPrice9,BuyingPrice10,BuyingVolume1,BuyingVolume2,BuyingVolume3,BuyingVolume4,BuyingVolume5,BuyingVolume6,BuyingVolume7,BuyingVolume8,BuyingVolume9,BuyingVolume10,CumulativeTransactionVolumeToTick,CumulativeTransactionAmountToTick,TotalCommissionedBuyingVolumeToTick,TotalCommissionedSellingVolumeToTick,LimitUpPrice,LimitDownPrice,WeightedAverageCommissionedBuyingPriceToTick,WeightedAverageCommissionedSellingPriceToTick
60,547,000031.SZ,93000000,38300,38600,38300,38600,38700,38800,38900,39000,39100,39200,39300,39400,39500,39600,94700,20800,4900,20400,38400,15800,41900,18900,12900,23200,38600,38400,38300,38200,38100,38000,37900,37800,37700,37600,15435,13700,16200,44700,151400,317700,26500,35000,15000,67100,221965,850959,1026935,1324200,42700,34900,37700,41000
61,548,000031.SZ,93000000,38300,38600,38300,38600,38700,38800,38900,39000,39100,39200,39300,39400,39500,39600,94700,20800,4900,20400,38400,15800,41900,18900,12900,23200,38600,38400,38300,38200,38100,38000,37900,37800,37700,37600,15435,13700,16200,44700,151400,317700,26500,35000,15000,67100,221965,850959,1026935,1324200,42700,34900,37700,41000
114,1093,000031.SZ,93003000,38300,38700,38300,38400,38400,38600,38700,38800,38900,39000,39100,39200,39300,39400,1600,60765,94100,43200,13000,23100,63600,21900,51900,18900,38300,38200,38100,38000,37900,37800,37700,37600,37500,37400,24800,135700,191600,245200,56000,101600,28200,182200,171900,33000,307200,1178902,1464700,1709965,42700,34900,37600,41000
148,1461,000031.SZ,93006000,38300,38700,38300,38400,38500,38600,38700,38800,38900,39000,39100,39200,39300,39400,8000,60265,93900,43200,13000,42700,63600,21900,51900,18900,38400,38300,38200,38100,38000,37900,37800,37700,37600,37500,28200,33800,150000,199900,68100,56400,212700,28200,107100,178900,317200,1217325,1408400,1742965,42700,34900,37600,40900
214,2105,000031.SZ,93009000,38300,38700,38300,38500,38500,38600,38700,38800,38900,39000,39100,39200,39300,39400,20700,60265,90900,38200,13000,42700,63600,21900,53200,18900,38400,38300,38200,38100,38000,37900,37800,37700,37600,37500,22100,32600,160000,199900,80100,56400,222700,28200,107100,181900,325500,1249200,1436100,1768965,42700,34900,37600,40900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216341,2131533,000031.SZ,145933000,38300,38700,37400,37600,37500,0,0,0,0,0,0,0,0,0,259800,0,0,0,0,0,0,0,0,0,37500,0,0,0,0,0,0,0,0,0,259800,180100,0,0,0,0,0,0,0,0,24011169,90646465,0,0,42700,34900,0,0
216424,2132368,000031.SZ,145942000,38300,38700,37400,37600,37500,0,0,0,0,0,0,0,0,0,284500,0,0,0,0,0,0,0,0,0,37500,0,0,0,0,0,0,0,0,0,284500,268700,0,0,0,0,0,0,0,0,24011169,90646465,0,0,42700,34900,0,0
216523,2133370,000031.SZ,145951000,38300,38700,37400,37600,37500,0,0,0,0,0,0,0,0,0,326500,0,0,0,0,0,0,0,0,0,37500,0,0,0,0,0,0,0,0,0,326500,236700,0,0,0,0,0,0,0,0,24011169,90646465,0,0,42700,34900,0,0
216653,2134611,000031.SZ,150000000,38300,38700,37400,37500,37600,37700,37800,37900,38000,38100,38200,38300,38400,38500,120600,224800,136900,59200,84800,74500,543000,35200,31600,68600,37500,37400,37300,37200,37100,37000,36900,36800,36700,36600,345100,447900,209000,358500,101700,491300,36200,106700,14500,38900,24338269,91873090,2575000,4272300,42700,34900,36900,40000
216654,2134612,000031.SZ,150000000,38300,38700,37400,37500,37600,37700,37800,37900,38000,38100,38200,38300,38400,38500,120600,224800,136900,59200,84800,74500,543000,35200,31600,68600,37500,37400,37300,37200,37100,37000,36900,36800,36700,36600,345100,447900,209000,358500,101700,491300,36200,106700,14500,38900,24338269,91873090,2575000,4272300,42700,34900,36900,40000

In [11]:
data.sort_values('TickTime').groupby('StockCode').rolling(5)['Index'].apply(lambda x: print(x))

0      547.0
36     548.0
37    1093.0
38    1461.0
39    2105.0
dtype: float64

TypeError: must be real number, not NoneType

In [8]:
func = NDayRegression().n_day_regression
vecfunc = np.vectorize(lambda x:
if type(x) == str:
    x
else:
    func)

SyntaxError: invalid syntax (2295398203.py, line 3)

In [ ]:
vecfunc(data.groupby('StockCode'))

In [ ]:
import inspect
inspect.getmembers(data.groupby('StockCode'))