In [1]:
import pandas as pd
import os
from utils.change_column_names import changeToName
from utils.feature_engineering import *
from utils.labels import *

from sklearn.pipeline import Pipeline

os.listdir()

['.git',
 '.idea',
 '.ipynb_checkpoints',
 'evaluation.py',
 'myModel_demo.py',
 'README.md',
 'readme.txt',
 'run.sh',
 'sample_tickdata.csv',
 'test.ipynb',
 'train.py',
 'utils']

In [2]:
data = pd.read_csv('sample_tickdata.csv')

In [3]:
data = changeToName(data)
data

,Index,StockCode,TickTime,OpeningPrice,HighestPriceToTick,LowestPriceToTick,LatestTransactionPriceToTick,SellingPrice1,SellingPrice2,SellingPrice3,...,BuyingVolume9,BuyingVolume10,CumulativeTransactionVolumeToTick,CumulativeTransactionAmountToTick,TotalCommissionedBuyingVolumeToTick,TotalCommissionedSellingVolumeToTick,LimitUpPrice,LimitDownPrice,WeightedAverageCommissionedBuyingPriceToTick,WeightedAverageCommissionedSellingPriceToTick
0,20,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,...,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
1,28,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,...,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
2,39,002156.SZ,93000000,170900,171000,170500,170900,171000,171200,171600,...,39200,800,517700,8846992,920700,1106300,190400,155800,163100,182900
3,40,002156.SZ,93000000,170900,171000,170500,170900,171000,171200,171600,...,39200,800,517700,8846992,920700,1106300,190400,155800,163100,182900
4,63,002153.SZ,93000000,148000,148800,147900,147900,148600,148700,148800,...,2000,10900,47700,706052,325100,239420,163700,133900,141800,153500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216652,2134584,600315.SH,150000000,316000,319600,311300,314400,314500,314600,314700,...,6500,41800,13108495,413087138,646837,1578100,353300,289100,310080,332090
216653,2134611,000031.SZ,150000000,38300,38700,37400,37500,37600,37700,37800,...,14500,38900,24338269,91873090,2575000,4272300,42700,34900,36900,40000
216654,2134612,000031.SZ,150000000,38300,38700,37400,37500,37600,37700,37800,...,14500,38900,24338269,91873090,2575000,4272300,42700,34900,36900,40000
216655,2134617,000039.SZ,150000000,70000,70100,69300,69300,69400,69500,69600,...,14800,31100,8793961,61227438,914489,2590773,77400,63400,68100,73500
216656,2134618,000039.SZ,150000000,70000,70100,69300,69300,69400,69500,69600,...,14800,31100,8793961,61227438,914489,2590773,77400,63400,68100,73500

In [4]:
pipeline = Pipeline([
    ('WeightedAvgPriceSpread', WeightedAvgComPriceSpread()),
    ('RollingComPriceSpread', RollingComPriceSpreadMean()),
    ('RollingTransPriceSpread', RollingTransPriceMean()),
    ('RollingComPriceSpreadDiff', RollingTransPriceMeanDiff()),
    ('RollingTransPriceMeanDiff', RollingTransPriceMeanDiff()),
#     ('Local Minima', LocalMinima())
])
datax = pipeline.fit_transform(data)

In [11]:
datax[datax['StockCode'] == '002056.SZ'][['LatestTransactionPriceToTick', 'RollingTransPriceMean5', 
                                         'RollingTransPriceMeanDiff5', 'TickTime']].sort_values('TickTime').head(10)

,LatestTransactionPriceToTick,RollingTransPriceMean5,RollingTransPriceMeanDiff5,TickTime
0,189400,NaN,NaN,93000000
1,189400,NaN,NaN,93000000
83,189400,NaN,NaN,93003000
128,189400,NaN,NaN,93006000
180,189300,189380.0,80.0,93009000
230,188800,189260.0,460.0,93012000
279,189600,189300.0,-300.0,93015000
335,190000,189420.0,-580.0,93018000
375,190500,189640.0,-860.0,93021000
426,190800,189940.0,-860.0,93024000

In [6]:
data[data['StockCode'] == '002056.SZ'].sort_values('TickTime').head(10)

,Index,StockCode,TickTime,OpeningPrice,HighestPriceToTick,LowestPriceToTick,LatestTransactionPriceToTick,SellingPrice1,SellingPrice2,SellingPrice3,...,BuyingVolume9,BuyingVolume10,CumulativeTransactionVolumeToTick,CumulativeTransactionAmountToTick,TotalCommissionedBuyingVolumeToTick,TotalCommissionedSellingVolumeToTick,LimitUpPrice,LimitDownPrice,WeightedAverageCommissionedBuyingPriceToTick,WeightedAverageCommissionedSellingPriceToTick
0,20,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,...,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
1,28,002056.SZ,93000000,189600,189600,188900,189400,189400,189500,189600,...,1800,3300,61000,1156242,700100,941100,208300,170500,185100,198100
83,776,002056.SZ,93003000,189600,189600,188900,189400,189500,189600,189700,...,38700,1800,81800,1550259,756500,1463900,208300,170500,185000,197300
128,1257,002056.SZ,93006000,189600,189600,188900,189400,189400,189500,189600,...,7400,800,102400,1940317,785100,1545800,208300,170500,185000,197100
180,1776,002056.SZ,93009000,189600,189600,188900,189300,189300,189400,189500,...,16900,7400,104900,1987610,795700,1574800,208300,170500,185100,197000
230,2267,002056.SZ,93012000,189600,189600,188800,188800,188900,189000,189100,...,800,4500,118000,2235188,790600,1576200,208300,170500,185000,197000
279,2756,002056.SZ,93015000,189600,189600,188800,189600,189600,189700,189800,...,700,38700,163000,3087245,807200,1538300,208300,170500,185100,197300
335,3275,002056.SZ,93018000,189600,190000,188800,190000,190200,190300,190400,...,1400,1200,217800,4127188,859200,1489500,208300,170500,185400,197500
375,3731,002056.SZ,93021000,189600,190500,188800,190500,190500,190600,190800,...,10400,9300,238300,4517287,869900,1483600,208300,170500,185500,197600
426,4226,002056.SZ,93024000,189600,190800,188800,190800,190600,190700,190800,...,1000,1400,268200,5086818,849500,1476800,208300,170500,185300,197700