In [1]:
import pandas as pd
import os
from utils.ChangeColumnNames import changeToName
from utils.FeatureEngineering import *

os.listdir()
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [2]:
data = pd.read_csv('tickdata_20221229.csv')
data.head()

,COLUMN01,COLUMN02,COLUMN03,COLUMN04,COLUMN05,COLUMN06,COLUMN07,COLUMN08,COLUMN09,COLUMN10,COLUMN11,COLUMN12,COLUMN13,COLUMN14,COLUMN15,COLUMN16,COLUMN17,COLUMN18,COLUMN19,COLUMN20,COLUMN21,COLUMN22,COLUMN23,COLUMN24,COLUMN25,COLUMN26,COLUMN27,COLUMN28,COLUMN29,COLUMN30,COLUMN31,COLUMN32,COLUMN33,COLUMN34,COLUMN35,COLUMN36,COLUMN37,COLUMN38,COLUMN39,COLUMN40,COLUMN41,COLUMN42,COLUMN43,COLUMN44,COLUMN45,COLUMN46,COLUMN47,COLUMN48,COLUMN49,COLUMN50,COLUMN51,COLUMN52,COLUMN53,COLUMN54,COLUMN55
0,0,600536.SH,93000000,559500,559500,559500,559500,559900,560000,561000,561800,562000,563000,564000,564300,564500,565000,5100,1000,300,3900,1700,200,2800,300,3800,2300,559500,559100,559000,558800,558500,558000,557500,557300,557100,556800,800,200,600,500,6100,10200,1100,400,600,100,81500,4559925,316600,549020,618200,505800,539980,585700
1,1,002080.SZ,93000000,217600,218300,217600,218100,218300,218500,218600,218800,218900,219000,219300,219400,219500,219700,900,1000,1000,5100,2000,9200,1500,500,1400,1800,218100,217700,217600,217300,217200,217000,216700,216600,216500,216300,1700,3400,3600,1000,300,1000,3000,8100,400,3000,23600,513802,126300,266600,238900,195500,213300,227300
2,2,002080.SZ,93000000,217600,218300,217600,218100,218300,218500,218600,218800,218900,219000,219300,219400,219500,219700,900,1000,1000,5100,2000,9200,1500,500,1400,1800,218100,217700,217600,217300,217200,217000,216700,216600,216500,216300,1700,3400,3600,1000,300,1000,3000,8100,400,3000,23600,513802,126300,266600,238900,195500,213300,227300
3,3,002081.SZ,93000000,49100,49100,49000,49100,49200,49300,49400,49500,49600,49700,49800,49900,50000,50100,1300,8000,42300,42400,86100,28300,13300,81600,30600,5000,49100,49000,48900,48800,48700,48600,48500,48400,48300,48200,35600,23800,15100,42400,28200,17700,54600,6900,13300,22700,25300,124213,595200,1206400,54000,44200,47700,51400
4,4,002081.SZ,93000000,49100,49100,49000,49100,49200,49300,49400,49500,49600,49700,49800,49900,50000,50100,1300,8000,42300,42400,86100,28300,13300,81600,30600,5000,49100,49000,48900,48800,48700,48600,48500,48400,48300,48200,35600,23800,15100,42400,28200,17700,54600,6900,13300,22700,25300,124213,595200,1206400,54000,44200,47700,51400

In [3]:
data = changeToName(data)
data.head()

,Index,StockCode,TickTime,OpeningPrice,HighestPriceToTick,LowestPriceToTick,LatestTransactionPriceToTick,SellingPrice1,SellingPrice2,SellingPrice3,SellingPrice4,SellingPrice5,SellingPrice6,SellingPrice7,SellingPrice8,SellingPrice9,SellingPrice10,SellingVolume1,SellingVolume2,SellingVolume3,SellingVolume4,SellingVolume5,SellingVolume6,SellingVolume7,SellingVolume8,SellingVolume9,SellingVolume10,BuyingPrice1,BuyingPrice2,BuyingPrice3,BuyingPrice4,BuyingPrice5,BuyingPrice6,BuyingPrice7,BuyingPrice8,BuyingPrice9,BuyingPrice10,BuyingVolume1,BuyingVolume2,BuyingVolume3,BuyingVolume4,BuyingVolume5,BuyingVolume6,BuyingVolume7,BuyingVolume8,BuyingVolume9,BuyingVolume10,CumulativeTransactionVolumeToTick,CumulativeTransactionAmountToTick,TotalCommissionedBuyingVolumeToTick,TotalCommissionedSellingVolumeToTick,LimitUpPrice,LimitDownPrice,WeightedAverageCommissionedBuyingPriceToTick,WeightedAverageCommissionedSellingPriceToTick
0,0,600536.SH,93000000,559500,559500,559500,559500,559900,560000,561000,561800,562000,563000,564000,564300,564500,565000,5100,1000,300,3900,1700,200,2800,300,3800,2300,559500,559100,559000,558800,558500,558000,557500,557300,557100,556800,800,200,600,500,6100,10200,1100,400,600,100,81500,4559925,316600,549020,618200,505800,539980,585700
1,1,002080.SZ,93000000,217600,218300,217600,218100,218300,218500,218600,218800,218900,219000,219300,219400,219500,219700,900,1000,1000,5100,2000,9200,1500,500,1400,1800,218100,217700,217600,217300,217200,217000,216700,216600,216500,216300,1700,3400,3600,1000,300,1000,3000,8100,400,3000,23600,513802,126300,266600,238900,195500,213300,227300
2,2,002080.SZ,93000000,217600,218300,217600,218100,218300,218500,218600,218800,218900,219000,219300,219400,219500,219700,900,1000,1000,5100,2000,9200,1500,500,1400,1800,218100,217700,217600,217300,217200,217000,216700,216600,216500,216300,1700,3400,3600,1000,300,1000,3000,8100,400,3000,23600,513802,126300,266600,238900,195500,213300,227300
3,3,002081.SZ,93000000,49100,49100,49000,49100,49200,49300,49400,49500,49600,49700,49800,49900,50000,50100,1300,8000,42300,42400,86100,28300,13300,81600,30600,5000,49100,49000,48900,48800,48700,48600,48500,48400,48300,48200,35600,23800,15100,42400,28200,17700,54600,6900,13300,22700,25300,124213,595200,1206400,54000,44200,47700,51400
4,4,002081.SZ,93000000,49100,49100,49000,49100,49200,49300,49400,49500,49600,49700,49800,49900,50000,50100,1300,8000,42300,42400,86100,28300,13300,81600,30600,5000,49100,49000,48900,48800,48700,48600,48500,48400,48300,48200,35600,23800,15100,42400,28200,17700,54600,6900,13300,22700,25300,124213,595200,1206400,54000,44200,47700,51400

In [4]:
wa = TransactionVolume()
datax = wa.transform(data)

In [5]:
datax[datax['StockCode'] == '600536.SH'].sort_values(['StockCode', 'TickTime']) \
    [['StockCode', 'TickTime', 'CumulativeTransactionVolumeToTick',
     'TransactionVolume']].head(50)

,StockCode,TickTime,CumulativeTransactionVolumeToTick,TransactionVolume
0,600536.SH,93000000,81500,81500.0
667,600536.SH,93002000,104650,23150.0
1226,600536.SH,93005000,112050,7400.0
1728,600536.SH,93008000,126550,14500.0
2228,600536.SH,93011000,157350,30800.0
2712,600536.SH,93014000,165750,8400.0
3224,600536.SH,93017000,181250,15500.0
3701,600536.SH,93020000,212550,31300.0
4183,600536.SH,93023000,246150,33600.0
4770,600536.SH,93026000,253850,7700.0
5187,600536.SH,93029000,263850,10000.0
5779,600536.SH,93032000,300150,36300.0
6212,600536.SH,93035000,333450,33300.0
6714,600536.SH,93038000,345350,11900.0
7210,600536.SH,93041000,356450,11100.0
7712,600536.SH,93044000,371850,15400.0
8208,600536.SH,93047000,383650,11800.0
8711,600536.SH,93050000,391750,8100.0
9212,600536.SH,93053000,410250,18500.0
9717,600536.SH,93056000,413950,3700.0
10258,600536.SH,93059000,428850,14900.0
10748,600536.SH,93102000,442250,13400.0
11251,600536.SH,93105000,474750,32500.0
11753,600536.SH,93108000,482150,7400.0
12258,600536.SH,93111000,485250,3100.0
12766,600536.SH,93114000,490950,5700.0
13259,600536.SH,93117000,492250,1300.0
13752,600536.SH,93120000,497950,5700.0
14254,600536.SH,93123000,520050,22100.0
14726,600536.SH,93126000,538450,18400.0
15261,600536.SH,93129000,547250,8800.0
15763,600536.SH,93132000,556050,8800.0
16309,600536.SH,93135000,576050,20000.0
16763,600536.SH,93138000,587550,11500.0
17259,600536.SH,93141000,594350,6800.0
17760,600536.SH,93144000,604750,10400.0
18261,600536.SH,93147000,631850,27100.0
18766,600536.SH,93150000,663950,32100.0
19261,600536.SH,93153000,684950,21000.0
19760,600536.SH,93156000,706650,21700.0
20255,600536.SH,93159000,727050,20400.0
20755,600536.SH,93202000,740350,13300.0
21249,600536.SH,93205000,750550,10200.0
21754,600536.SH,93208000,761650,11100.0
22244,600536.SH,93211000,770450,8800.0
22790,600536.SH,93214000,775250,4800.0
23240,600536.SH,93217000,797650,22400.0
23785,600536.SH,93220000,832650,35000.0
24202,600536.SH,93223000,843750,11100.0
24793,600536.SH,93226000,853850,10100.0